"""Turn a repository into an embedded, stored Snapshot."""

import os
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Protocol

from repolens import chunking
from repolens.chunking import LANGUAGES, Chunk, chunk_file
from repolens.embedding import Embedder
from repolens.snapshot import RepoRef, Snapshot
from repolens.store import ChunkStore

MAX_FILES = 2000
MAX_FILE_BYTES = 256_000

VENDORED_DIRS = frozenset(
    {
        "node_modules",
        "vendor",
        "vendored",
        "third_party",
        "third-party",
        "site-packages",
        "venv",
        "__pycache__",
        "__generated__",
    }
)
GENERATED_SUFFIXES = (".d.ts", "_pb2.py", "_pb2_grpc.py", ".generated.ts", ".gen.ts")
GENERATED_MARKERS = ("@generated", "do not edit", "auto-generated", "autogenerated")


class IngestError(Exception):
    """The repository can't be ingested."""


class SnapshotSource(Protocol):
    def resolve(self, repo: RepoRef) -> Snapshot:
        """Pin a repository ref to a commit SHA."""
        ...

    def download(self, snapshot: Snapshot, dest: Path) -> None:
        """Write the files of the Snapshot into `dest`."""
        ...


@dataclass(frozen=True)
class IngestResult:
    snapshot: Snapshot
    file_count: int
    chunk_count: int
    created: bool


def ingest(
    repo: RepoRef, source: SnapshotSource, embedder: Embedder, store: ChunkStore
) -> IngestResult:
    """Chunk, embed and store a repository's Python and TypeScript sources.

    Each Snapshot is ingested once per index version. Later calls return the stored counts.
    """
    snapshot = source.resolve(repo)
    version = index_version(embedder)
    stored = store.find(snapshot)
    if stored and stored.index_version == version:
        return IngestResult(snapshot, stored.file_count, stored.chunk_count, created=False)
    if stored:
        store.delete(snapshot)

    with TemporaryDirectory() as tmp:
        source.download(snapshot, Path(tmp))
        files = _source_files(Path(tmp))
    if len(files) > MAX_FILES:
        raise IngestError(f"{snapshot} has {len(files)} source files, the limit is {MAX_FILES}")

    chunks = [chunk for path, text in files for chunk in chunk_file(path, text)]
    embeddings = embedder.embed([_embedding_text(chunk) for chunk in chunks])
    store.save(snapshot, len(files), chunks, embeddings, embedder.model, version)
    return IngestResult(snapshot, len(files), len(chunks), created=True)


def index_version(embedder: Embedder) -> str:
    """What a Snapshot's stored Chunks depend on: the chunker and the embedding model."""
    return f"chunker-{chunking.CHUNKER_VERSION}/{embedder.model}"


def _source_files(root: Path) -> list[tuple[str, str]]:
    """Return (path, text) for each source file, skipping vendored and generated code."""
    files: list[tuple[str, str]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(
            d for d in dirnames if not d.startswith(".") and d not in VENDORED_DIRS
        )
        for filename in sorted(filenames):
            path = Path(dirpath, filename)
            text = _read_source(path)
            if text is not None:
                files.append((path.relative_to(root).as_posix(), text))
    return files


def _read_source(path: Path) -> str | None:
    if path.suffix not in LANGUAGES or path.name.endswith(GENERATED_SUFFIXES):
        return None
    if not path.is_file() or path.stat().st_size > MAX_FILE_BYTES:
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None
    head = "\n".join(text.splitlines()[:5]).lower()
    if "\x00" in text or any(marker in head for marker in GENERATED_MARKERS):
        return None
    return text


def _embedding_text(chunk: Chunk) -> str:
    return f"{chunk.path}\n{chunk.symbol}\n\n{chunk.text}"
